'use strict';
function html(nonce) {
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';"><style nonce="${nonce}">
body{font:14px/1.5 var(--vscode-font-family,system-ui);color:var(--vscode-foreground,#ddd);background:var(--vscode-editor-background,#181a22);max-width:900px;margin:auto;padding:24px;box-sizing:border-box}h1{font-size:26px;margin:0}.sub,.meta,#status,#summary-status{color:var(--vscode-descriptionForeground,#aaa)}.sub{margin:4px 0 18px}.toolbar,.actions{display:flex;gap:16px;flex-wrap:wrap;margin:14px 0}.search{display:flex;gap:8px;flex-wrap:wrap}input{flex:1 1 180px;min-width:0;padding:11px;border:1px solid var(--vscode-input-border,#555);background:var(--vscode-input-background,#252936);color:var(--vscode-input-foreground,#fff);font:inherit;border-radius:6px}button{cursor:pointer;font:inherit;border:0;border-radius:5px;padding:9px 13px;background:var(--vscode-button-background,#246645);color:var(--vscode-button-foreground,#fff)}button:focus-visible,input:focus-visible{outline:2px solid var(--vscode-focusBorder,#63d297);outline-offset:2px}.link{background:transparent;color:var(--vscode-textLink-foreground,#63d297);padding:0}.card{margin:12px 0;padding:17px;border:1px solid var(--vscode-panel-border,#444);border-radius:9px;background:var(--vscode-sideBar-background,#20232c);overflow-wrap:anywhere}.title{font-size:16px;font-weight:650;margin:7px 0}.meta{font-size:12px;display:flex;gap:10px;flex-wrap:wrap}.summary{margin:10px 0;font-size:15px}.summary-note{font-size:11px;color:var(--vscode-descriptionForeground,#aaa)}.snippet{white-space:pre-wrap;margin:8px 0;max-height:130px;overflow:auto;font-size:13px}.full-chunk{max-height:360px;overflow:auto}.answer{font-size:16px;font-weight:600;margin:12px 0}.citation{border-left:3px solid var(--vscode-textLink-foreground,#63d297);padding:5px 10px;margin:8px 0;white-space:pre-wrap}.actions{margin-bottom:0}#status,#summary-status{font-size:12px;min-height:18px}details summary{cursor:pointer}.empty{padding:20px 0}#stop{display:none}
</style></head><body><h1>Chat Seek</h1><p class="sub">Find a conversation or ask a question about past chats.</p><form class="search" id="form"><input id="q" aria-label="Describe a past chat or ask a question" type="search" placeholder="e.g. what was the launch date?" autocomplete="off"><button type="submit">Search</button><button type="button" id="stop">Stop</button></form><div class="toolbar"><button class="link" id="configure">Configure summaries</button><button class="link" id="refresh">Refresh chats</button><button class="link" id="pin">Pin search tab</button></div><div id="status" role="status">Loading local chats…</div><div id="summary-status" role="status">Search and Laya ranking stay local. Optional AI summaries use your provider.</div><div id="results"></div><script nonce="${nonce}">
const api=acquireVsCodeApi(),q=document.getElementById('q'),results=document.getElementById('results');
let items=[],summaries=new Map(),mode='chat';q.value=api.getState?.()?.query||'';
function el(tag,cls,text){const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function action(label,type,item){const b=el('button','link',label);b.addEventListener('click',()=>api.postMessage({type,key:item.key,id:item.id,line:item.matches?.[0]?.line??item.line}));return b;}
function cardFor(item){const card=el('article','card');if(item.id)card.dataset.id=item.id;const meta=el('div','meta');meta.append(el('span','',item.source));const date=el('time','',item.relativeDate||'Date unknown');date.title=item.fullDate||'';meta.append(date);card.append(meta);if(item.mode==='question'){card.append(el('div','title',item.title||item.session));card.append(el('div','answer',item.answer||(item.verification==='pending'?'Checking answer and citation…':'Potential answer in this chunk')));if(item.provider)card.append(el('div','summary-note','Answer extracted by '+item.provider+' · citation verified against source text'));if(item.citation)card.append(el('blockquote','citation',item.citation));const details=el('details','');details.append(el('summary','','Read full original chunk'));details.append(el('div','snippet full-chunk',item.chunk));card.append(details);const actions=el('div','actions');actions.append(action('Open full chunk','openChunk',item));actions.append(action('Read chat context','open',item));if(item.canResume)actions.append(action('Resume in '+item.source,'resume',item));card.append(actions);return card;}const summary=summaries.get(item.key)||item.summary;card.append(el('div','title',summary?.text||item.title));if(summary)card.append(el('div','summary-note','AI summary of sampled messages · '+summary.provider));const details=el('details','');details.open=!summary;details.append(el('summary','','Matching excerpt'));details.append(el('div','snippet',item.matches[0]?.text||''));card.append(details);const actions=el('div','actions');actions.append(action('Read excerpt','open',item));if(item.canResume)actions.append(action('Resume in '+item.source,'resume',item));card.append(actions);return card;}
function render(){results.replaceChildren();if(!items.length){results.append(el('p','empty',mode==='question'?'Scanning original chats for an answer…':'No matching chats yet. Try a project name or describe the work.'));return;}for(const item of items)results.append(cardFor(item));}
document.getElementById('form').addEventListener('submit',e=>{e.preventDefault();const query=q.value.trim();if(query){api.setState?.({query});api.postMessage({type:'search',query});document.getElementById('stop').style.display='inline-block';}});
document.getElementById('stop').addEventListener('click',()=>{api.postMessage({type:'stop'});document.getElementById('stop').style.display='none';});
for(const id of ['configure','refresh','pin'])document.getElementById(id).addEventListener('click',()=>api.postMessage({type:id}));
window.addEventListener('message',e=>{const m=e.data;if(m.type==='status'){document.getElementById('status').textContent=m.text;if(/^Finished|^Stopped|^Question scan stopped/.test(m.text))document.getElementById('stop').style.display='none';}if(m.type==='searchDone'||m.type==='searchRunning')document.getElementById('stop').style.display=m.running?'inline-block':'none';if(m.type==='summaryStatus')document.getElementById('summary-status').textContent=m.text;if(m.type==='mode'){mode=m.mode;render();}if(m.type==='results'){items=m.items;mode=items[0]?.mode||mode;summaries.clear();render();}if(m.type==='questionResult'){if(m.prepend)items.unshift(m.item);else items.push(m.item);results.querySelector('.empty')?.remove();if(m.prepend)results.prepend(cardFor(m.item));else results.append(cardFor(m.item));}if(m.type==='questionUpdate'){const at=items.findIndex(x=>x.id===m.id);if(at>=0){items[at]=m.item;const old=[...results.children].find(x=>x.dataset.id===m.id);const next=cardFor(m.item);next.querySelector('details').open=old?.querySelector('details')?.open||false;if(m.item.verification==='verified'){items.splice(at,1);items.unshift(m.item);results.prepend(next);old?.remove();}else old?.replaceWith(next);}}if(m.type==='questionRemove'){items=items.filter(x=>x.id!==m.id);[...results.children].find(x=>x.dataset.id===m.id)?.remove();if(!items.length)render();}if(m.type==='summary'){summaries.set(m.key,m.summary);render();}});q.focus();api.postMessage({type:'ready'});
</script></body></html>`;
}
module.exports = { html };
