'use strict';
function html(nonce) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';"><style nonce="${nonce}">
  :root{color-scheme:dark}body{font:14px/1.5 var(--vscode-font-family);color:var(--vscode-foreground);background:var(--vscode-editor-background);max-width:900px;margin:0 auto;padding:36px 24px}h1{font-size:27px;letter-spacing:-.04em;margin:0 0 3px}.sub{color:var(--vscode-descriptionForeground);margin:0 0 22px}.search{display:flex;gap:8px}input{flex:1;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-input-border,#555);border-radius:6px;padding:11px 13px;font:inherit;min-width:0}input:focus{outline:1px solid var(--vscode-focusBorder)}button{border:0;border-radius:6px;padding:10px 15px;background:var(--vscode-button-background);color:var(--vscode-button-foreground);font:inherit;cursor:pointer}button:hover{background:var(--vscode-button-hoverBackground)}#status{min-height:24px;color:var(--vscode-descriptionForeground);margin:13px 0 18px}.card{border:1px solid var(--vscode-panel-border,#555);border-radius:9px;padding:17px 18px;margin:11px 0;background:var(--vscode-sideBar-background)}.top{display:flex;justify-content:space-between;gap:12px}.title{font-size:16px;font-weight:650;line-height:1.3;overflow-wrap:anywhere}.meta{color:var(--vscode-descriptionForeground);font-size:12px;white-space:nowrap}.snippet{white-space:pre-wrap;overflow-wrap:anywhere;max-height:130px;overflow:hidden;color:var(--vscode-foreground);opacity:.88;margin:10px 0 12px}.open{background:transparent;color:var(--vscode-textLink-foreground);padding:0}.open:hover{text-decoration:underline;background:transparent}.empty{color:var(--vscode-descriptionForeground);padding:22px 0}
  </style></head><body><h1>Chat Seek</h1><p class="sub">Describe the conversation you remember. Search stays on your machine.</p><form class="search" id="form"><input id="q" type="search" placeholder="e.g. the Claude chat where we built JevBench" autocomplete="off" autofocus><button>Find chats</button></form><div id="status">Loading local chat index…</div><div id="results"></div><script nonce="${nonce}">
  const vscode=acquireVsCodeApi(),form=document.getElementById('form'),q=document.getElementById('q'),status=document.getElementById('status'),results=document.getElementById('results');
  form.addEventListener('submit',e=>{e.preventDefault();const query=q.value.trim();if(query){status.textContent='Searching…';vscode.postMessage({type:'search',query});}});
  window.addEventListener('message',e=>{const m=e.data;if(m.type==='status'){status.textContent=m.text;}if(m.type==='results'){results.replaceChildren();if(!m.items.length){const x=document.createElement('p');x.className='empty';x.textContent='No matching chats found. Try another description.';results.append(x);return;}for(const item of m.items){const card=document.createElement('article');card.className='card';const top=document.createElement('div');top.className='top';const title=document.createElement('div');title.className='title';title.textContent=item.title;const meta=document.createElement('span');meta.className='meta';meta.textContent=item.source;top.append(title,meta);const sn=document.createElement('div');sn.className='snippet';sn.textContent=item.matches[0]?.text||'';const btn=document.createElement('button');btn.className='open';btn.textContent='Read conversation →';btn.addEventListener('click',()=>vscode.postMessage({type:'open',key:item.key,line:item.matches[0]?.line}));card.append(top,sn,btn);results.append(card);}}});q.focus();
  </script></body></html>`;
}
module.exports = { html };
