'use strict';
function html(nonce) {
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';"><style nonce="${nonce}">
body{font:14px/1.5 var(--vscode-font-family,system-ui);color:var(--vscode-foreground,#ddd);background:var(--vscode-editor-background,#181a22);max-width:900px;margin:auto;padding:24px;box-sizing:border-box}h1{font-size:26px;margin:0}.sub,.meta,#status,#summary-status{color:var(--vscode-descriptionForeground,#aaa)}.sub{margin:4px 0 18px}.toolbar,.actions{display:flex;gap:16px;flex-wrap:wrap;margin:14px 0}.search{display:flex;gap:8px;flex-wrap:wrap}input{flex:1 1 180px;min-width:0;padding:11px;border:1px solid var(--vscode-input-border,#555);background:var(--vscode-input-background,#252936);color:var(--vscode-input-foreground,#fff);font:inherit;border-radius:6px}button{cursor:pointer;font:inherit;border:0;border-radius:5px;padding:9px 13px;background:var(--vscode-button-background,#246645);color:var(--vscode-button-foreground,#fff)}button:focus-visible,input:focus-visible{outline:2px solid var(--vscode-focusBorder,#63d297);outline-offset:2px}.link{background:transparent;color:var(--vscode-textLink-foreground,#63d297);padding:0}.card{margin:12px 0;padding:17px;border:1px solid var(--vscode-panel-border,#444);border-radius:9px;background:var(--vscode-sideBar-background,#20232c);overflow-wrap:anywhere}.title{font-size:16px;font-weight:650;margin:7px 0}.meta{font-size:12px;display:flex;gap:10px;flex-wrap:wrap}.summary{margin:10px 0;font-size:15px}.summary-note{font-size:11px;color:var(--vscode-descriptionForeground,#aaa)}.snippet{white-space:pre-wrap;margin:8px 0;max-height:130px;overflow:auto;font-size:13px}.actions{margin-bottom:0}#status,#summary-status{font-size:12px;min-height:18px}details summary{cursor:pointer}.empty{padding:20px 0}
</style></head><body><h1>Chat Seek</h1><p class="sub">Find the conversation you remember.</p><form class="search" id="form"><input id="q" aria-label="Describe a past chat" type="search" placeholder="e.g. where we built JevBench" autocomplete="off"><button type="submit">Find chats</button></form><div class="toolbar"><button class="link" id="configure">Configure summaries</button><button class="link" id="refresh">Refresh chats</button><button class="link" id="pin">Pin search tab</button></div><div id="status" role="status">Loading local chats…</div><div id="summary-status" role="status">Search and Laya ranking stay local. Optional AI summaries use your provider.</div><div id="results"></div><script nonce="${nonce}">
const api=acquireVsCodeApi(),q=document.getElementById('q'),results=document.getElementById('results');
let items=[],summaries=new Map();q.value=api.getState?.()?.query||'';
function el(tag,cls,text){const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function action(label,type,item){const b=el('button','link',label);b.addEventListener('click',()=>api.postMessage({type,key:item.key,line:item.matches[0]?.line}));return b;}
function render(){results.replaceChildren();if(!items.length){results.append(el('p','empty','No matching chats yet. Try a project name or describe the work.'));return;}for(const item of items){const card=el('article','card');const meta=el('div','meta');meta.append(el('span','',item.source));const date=el('time','',item.relativeDate||'Date unknown');date.title=item.fullDate||'';meta.append(date);card.append(meta);const summary=summaries.get(item.key)||item.summary;card.append(el('div','title',summary?.text||item.title));if(summary)card.append(el('div','summary-note','AI summary of sampled messages · '+summary.provider));const details=el('details','');details.open=!summary;details.append(el('summary','','Matching excerpt'));details.append(el('div','snippet',item.matches[0]?.text||''));card.append(details);const actions=el('div','actions');actions.append(action('Read excerpt','open',item));if(item.canResume)actions.append(action('Resume in '+item.source,'resume',item));card.append(actions);results.append(card);}}
document.getElementById('form').addEventListener('submit',e=>{e.preventDefault();const query=q.value.trim();if(query){api.setState?.({query});api.postMessage({type:'search',query});}});
for(const id of ['configure','refresh','pin'])document.getElementById(id).addEventListener('click',()=>api.postMessage({type:id}));
window.addEventListener('message',e=>{const m=e.data;if(m.type==='status')document.getElementById('status').textContent=m.text;if(m.type==='summaryStatus')document.getElementById('summary-status').textContent=m.text;if(m.type==='results'){items=m.items;summaries.clear();render();}if(m.type==='summary'){summaries.set(m.key,m.summary);render();}});q.focus();api.postMessage({type:'ready'});
</script></body></html>`;
}
module.exports = { html };
